server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy /api/ requests to Java 17 Spring Boot backend container
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Proxy /rates requests to Backend
    location /rates {
        proxy_pass http://backend:8080/rates;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
